// Code generated by MockGen. DO NOT EDIT.
// Source: state.go
//
// Generated by this command:
//
//	mockgen -source state.go -destination state_mock.go -package reference
//

// Package reference is a generated GoMock package.
package reference

import (
	reflect "reflect"

	commit "github.com/0xsoniclabs/carmen/go/database/vt/commit"
	trie "github.com/0xsoniclabs/carmen/go/database/vt/reference/trie"
	gomock "go.uber.org/mock/gomock"
)

// MockTrie is a mock of Trie interface.
type MockTrie struct {
	ctrl     *gomock.Controller
	recorder *MockTrieMockRecorder
	isgomock struct{}
}

// MockTrieMockRecorder is the mock recorder for MockTrie.
type MockTrieMockRecorder struct {
	mock *MockTrie
}

// NewMockTrie creates a new mock instance.
func NewMockTrie(ctrl *gomock.Controller) *MockTrie {
	mock := &MockTrie{ctrl: ctrl}
	mock.recorder = &MockTrieMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrie) EXPECT() *MockTrieMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTrie) Commit() commit.Commitment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(commit.Commitment)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTrieMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTrie)(nil).Commit))
}

// Config mocks base method.
func (m *MockTrie) Config() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(any)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockTrieMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockTrie)(nil).Config))
}

// Get mocks base method.
func (m *MockTrie) Get(key trie.Key) trie.Value {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(trie.Value)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTrieMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTrie)(nil).Get), key)
}

// Set mocks base method.
func (m *MockTrie) Set(key trie.Key, value trie.Value) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, value)
}

// Set indicates an expected call of Set.
func (mr *MockTrieMockRecorder) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockTrie)(nil).Set), key, value)
}
