// Code generated by MockGen. DO NOT EDIT.
// Source: flat_test.go
//
// Generated by this command:
//
//	mockgen -source flat_test.go -destination flat_mock_test.go -package flat
//

// Package flat is a generated GoMock package.
package flat

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mock_Reader is a mock of _Reader interface.
type Mock_Reader struct {
	ctrl     *gomock.Controller
	recorder *Mock_ReaderMockRecorder
	isgomock struct{}
}

// Mock_ReaderMockRecorder is the mock recorder for Mock_Reader.
type Mock_ReaderMockRecorder struct {
	mock *Mock_Reader
}

// NewMock_Reader creates a new mock instance.
func NewMock_Reader(ctrl *gomock.Controller) *Mock_Reader {
	mock := &Mock_Reader{ctrl: ctrl}
	mock.recorder = &Mock_ReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_Reader) EXPECT() *Mock_ReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *Mock_Reader) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *Mock_ReaderMockRecorder) Read(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*Mock_Reader)(nil).Read), p)
}

// Mock_Writer is a mock of _Writer interface.
type Mock_Writer struct {
	ctrl     *gomock.Controller
	recorder *Mock_WriterMockRecorder
	isgomock struct{}
}

// Mock_WriterMockRecorder is the mock recorder for Mock_Writer.
type Mock_WriterMockRecorder struct {
	mock *Mock_Writer
}

// NewMock_Writer creates a new mock instance.
func NewMock_Writer(ctrl *gomock.Controller) *Mock_Writer {
	mock := &Mock_Writer{ctrl: ctrl}
	mock.recorder = &Mock_WriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_Writer) EXPECT() *Mock_WriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *Mock_Writer) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *Mock_WriterMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*Mock_Writer)(nil).Write), p)
}
