// Code generated by MockGen. DO NOT EDIT.
// Source: external_state.go
//
// Generated by this command:
//
//	mockgen -source external_state.go -destination external_state_mocks.go -package externalstate
//

// Package externalstate is a generated GoMock package.
package externalstate

/*
#include <stdlib.h>
#include "state/c_state.h"
*/
import "C"

import (
	reflect "reflect"
	unsafe "unsafe"

	gomock "go.uber.org/mock/gomock"
)

// MockexternalBindings is a mock of externalBindings interface.
type MockexternalBindings struct {
	ctrl     *gomock.Controller
	recorder *MockexternalBindingsMockRecorder
	isgomock struct{}
}

// MockexternalBindingsMockRecorder is the mock recorder for MockexternalBindings.
type MockexternalBindingsMockRecorder struct {
	mock *MockexternalBindings
}

// NewMockexternalBindings creates a new mock instance.
func NewMockexternalBindings(ctrl *gomock.Controller) *MockexternalBindings {
	mock := &MockexternalBindings{ctrl: ctrl}
	mock.recorder = &MockexternalBindingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexternalBindings) EXPECT() *MockexternalBindingsMockRecorder {
	return m.recorder
}

// AccountExists mocks base method.
func (m *MockexternalBindings) AccountExists(state, address, outExists unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountExists", state, address, outExists)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// AccountExists indicates an expected call of AccountExists.
func (mr *MockexternalBindingsMockRecorder) AccountExists(state, address, outExists any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountExists", reflect.TypeOf((*MockexternalBindings)(nil).AccountExists), state, address, outExists)
}

// Apply mocks base method.
func (m *MockexternalBindings) Apply(state unsafe.Pointer, block C.uint64_t, update unsafe.Pointer, updateLength C.uint64_t) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", state, block, update, updateLength)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockexternalBindingsMockRecorder) Apply(state, block, update, updateLength any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockexternalBindings)(nil).Apply), state, block, update, updateLength)
}

// Close mocks base method.
func (m *MockexternalBindings) Close(database unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", database)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockexternalBindingsMockRecorder) Close(database any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockexternalBindings)(nil).Close), database)
}

// Flush mocks base method.
func (m *MockexternalBindings) Flush(database unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", database)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockexternalBindingsMockRecorder) Flush(database any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockexternalBindings)(nil).Flush), database)
}

// GetArchiveState mocks base method.
func (m *MockexternalBindings) GetArchiveState(database unsafe.Pointer, block C.uint64_t, outState *unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchiveState", database, block, outState)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetArchiveState indicates an expected call of GetArchiveState.
func (mr *MockexternalBindingsMockRecorder) GetArchiveState(database, block, outState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchiveState", reflect.TypeOf((*MockexternalBindings)(nil).GetArchiveState), database, block, outState)
}

// GetBalance mocks base method.
func (m *MockexternalBindings) GetBalance(state, address, outBalance unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", state, address, outBalance)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockexternalBindingsMockRecorder) GetBalance(state, address, outBalance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockexternalBindings)(nil).GetBalance), state, address, outBalance)
}

// GetCode mocks base method.
func (m *MockexternalBindings) GetCode(state, address, outCode unsafe.Pointer, outSize *C.uint32_t) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", state, address, outCode, outSize)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetCode indicates an expected call of GetCode.
func (mr *MockexternalBindingsMockRecorder) GetCode(state, address, outCode, outSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockexternalBindings)(nil).GetCode), state, address, outCode, outSize)
}

// GetCodeHash mocks base method.
func (m *MockexternalBindings) GetCodeHash(state, address, outHash unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeHash", state, address, outHash)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetCodeHash indicates an expected call of GetCodeHash.
func (mr *MockexternalBindingsMockRecorder) GetCodeHash(state, address, outHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeHash", reflect.TypeOf((*MockexternalBindings)(nil).GetCodeHash), state, address, outHash)
}

// GetCodeSize mocks base method.
func (m *MockexternalBindings) GetCodeSize(state, address unsafe.Pointer, outSize *C.uint32_t) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeSize", state, address, outSize)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetCodeSize indicates an expected call of GetCodeSize.
func (mr *MockexternalBindingsMockRecorder) GetCodeSize(state, address, outSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeSize", reflect.TypeOf((*MockexternalBindings)(nil).GetCodeSize), state, address, outSize)
}

// GetHash mocks base method.
func (m *MockexternalBindings) GetHash(state, outHash unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHash", state, outHash)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetHash indicates an expected call of GetHash.
func (mr *MockexternalBindingsMockRecorder) GetHash(state, outHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHash", reflect.TypeOf((*MockexternalBindings)(nil).GetHash), state, outHash)
}

// GetLiveState mocks base method.
func (m *MockexternalBindings) GetLiveState(database unsafe.Pointer, outState *unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLiveState", database, outState)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetLiveState indicates an expected call of GetLiveState.
func (mr *MockexternalBindingsMockRecorder) GetLiveState(database, outState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLiveState", reflect.TypeOf((*MockexternalBindings)(nil).GetLiveState), database, outState)
}

// GetMemoryFootprint mocks base method.
func (m *MockexternalBindings) GetMemoryFootprint(database unsafe.Pointer, outBuffer **C.char, outSize *C.uint64_t) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryFootprint", database, outBuffer, outSize)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetMemoryFootprint indicates an expected call of GetMemoryFootprint.
func (mr *MockexternalBindingsMockRecorder) GetMemoryFootprint(database, outBuffer, outSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryFootprint", reflect.TypeOf((*MockexternalBindings)(nil).GetMemoryFootprint), database, outBuffer, outSize)
}

// GetNonce mocks base method.
func (m *MockexternalBindings) GetNonce(state, address, outNonce unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", state, address, outNonce)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockexternalBindingsMockRecorder) GetNonce(state, address, outNonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockexternalBindings)(nil).GetNonce), state, address, outNonce)
}

// GetStorageValue mocks base method.
func (m *MockexternalBindings) GetStorageValue(state, address, key, outValue unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageValue", state, address, key, outValue)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// GetStorageValue indicates an expected call of GetStorageValue.
func (mr *MockexternalBindingsMockRecorder) GetStorageValue(state, address, key, outValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageValue", reflect.TypeOf((*MockexternalBindings)(nil).GetStorageValue), state, address, key, outValue)
}

// OpenDatabase mocks base method.
func (m *MockexternalBindings) OpenDatabase(schema C.uint8_t, liveImpl *C.char, liveImplLen C.int, archiveImpl *C.char, archiveImplLen C.int, dir *C.char, dirLen C.int, outDatabase *unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenDatabase", schema, liveImpl, liveImplLen, archiveImpl, archiveImplLen, dir, dirLen, outDatabase)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// OpenDatabase indicates an expected call of OpenDatabase.
func (mr *MockexternalBindingsMockRecorder) OpenDatabase(schema, liveImpl, liveImplLen, archiveImpl, archiveImplLen, dir, dirLen, outDatabase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenDatabase", reflect.TypeOf((*MockexternalBindings)(nil).OpenDatabase), schema, liveImpl, liveImplLen, archiveImpl, archiveImplLen, dir, dirLen, outDatabase)
}

// ReleaseDatabase mocks base method.
func (m *MockexternalBindings) ReleaseDatabase(database unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseDatabase", database)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// ReleaseDatabase indicates an expected call of ReleaseDatabase.
func (mr *MockexternalBindingsMockRecorder) ReleaseDatabase(database any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseDatabase", reflect.TypeOf((*MockexternalBindings)(nil).ReleaseDatabase), database)
}

// ReleaseMemoryFootprintBuffer mocks base method.
func (m *MockexternalBindings) ReleaseMemoryFootprintBuffer(buffer *C.char, size C.uint64_t) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseMemoryFootprintBuffer", buffer, size)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// ReleaseMemoryFootprintBuffer indicates an expected call of ReleaseMemoryFootprintBuffer.
func (mr *MockexternalBindingsMockRecorder) ReleaseMemoryFootprintBuffer(buffer, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseMemoryFootprintBuffer", reflect.TypeOf((*MockexternalBindings)(nil).ReleaseMemoryFootprintBuffer), buffer, size)
}

// ReleaseState mocks base method.
func (m *MockexternalBindings) ReleaseState(state unsafe.Pointer) C.enum_Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseState", state)
	ret0, _ := ret[0].(C.enum_Result)
	return ret0
}

// ReleaseState indicates an expected call of ReleaseState.
func (mr *MockexternalBindingsMockRecorder) ReleaseState(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseState", reflect.TypeOf((*MockexternalBindings)(nil).ReleaseState), state)
}
